//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.zqy_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="zqy_ServiceReference.IMyFirstService")]
    public interface IMyFirstService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/DoWork", ReplyAction="http://tempuri.org/IMyFirstService/DoWorkResponse")]
        string DoWork(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/DoWork", ReplyAction="http://tempuri.org/IMyFirstService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyFirstServiceChannel : Test.zqy_ServiceReference.IMyFirstService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyFirstServiceClient : System.ServiceModel.ClientBase<Test.zqy_ServiceReference.IMyFirstService>, Test.zqy_ServiceReference.IMyFirstService {
        
        public MyFirstServiceClient() {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFirstServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork(string Name) {
            return base.Channel.DoWork(Name);
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync(string Name) {
            return base.Channel.DoWorkAsync(Name);
        }
    }
}
